/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessCodeToolRouteImport } from './routes/access-code-tool'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessCodeToolRoute = AccessCodeToolRouteImport.update({
  id: '/access-code-tool',
  path: '/access-code-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-code-tool': typeof AccessCodeToolRoute
  '/board/$boardId': typeof BoardBoardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-code-tool': typeof AccessCodeToolRoute
  '/board/$boardId': typeof BoardBoardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-code-tool': typeof AccessCodeToolRoute
  '/board/$boardId': typeof BoardBoardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/access-code-tool' | '/board/$boardId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/access-code-tool' | '/board/$boardId'
  id: '__root__' | '/' | '/access-code-tool' | '/board/$boardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessCodeToolRoute: typeof AccessCodeToolRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-code-tool': {
      id: '/access-code-tool'
      path: '/access-code-tool'
      fullPath: '/access-code-tool'
      preLoaderRoute: typeof AccessCodeToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessCodeToolRoute: AccessCodeToolRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
